services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codinviec-consumer
    env_file:
      - .env
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    networks:
      - codinviec_codinviec-backend
    restart: unless-stopped

networks:
  codinviec_codinviec-backend:
    external: true
