services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codinviec-consumer
    env_file:
      - .env
    networks:
      - codinviec_codinviec-backend
    restart: unless-stopped

networks:
  codinviec_codinviec-backend:
    external: true
